"""initial schema

Revision ID: c981d9eb4d2d
Revises:
Create Date: 2026-09-26 16:49:12.117362
"""

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c981d9eb4d2d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "security_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_audit_events_actor_id"),
        "security_audit_events",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_events_created_at"),
        "security_audit_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_events_event_type"),
        "security_audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_events_resource_id"),
        "security_audit_events",
        ["resource_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("google_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("session_generation", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_subject"),
    )
    op.create_table(
        "gmail_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("mailbox_address", sa.String(length=320), nullable=False),
        sa.Column("encrypted_token_bundle", sa.Text(), nullable=True),
        sa.Column("granted_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("connection_state", sa.String(length=32), nullable=False),
        sa.Column("connection_generation", sa.Integer(), nullable=False),
        sa.Column("last_history_id", sa.String(length=64), nullable=True),
        sa.Column("pending_sync", sa.Boolean(), nullable=False),
        sa.Column("watch_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_consent", sa.Boolean(), nullable=False),
        sa.Column("label_write_consent", sa.Boolean(), nullable=False),
        sa.Column("disclosure_version", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_gmail_account_user"),
    )
    op.create_index(op.f("ix_gmail_accounts_user_id"), "gmail_accounts", ["user_id"], unique=False)
    op.create_table(
        "oauth_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("browser_session_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("state_digest", sa.String(length=64), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("encrypted_verifier", sa.Text(), nullable=False),
        sa.Column("return_path", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_digest"),
    )
    op.create_index(
        op.f("ix_oauth_attempts_browser_session_id"),
        "oauth_attempts",
        ["browser_session_id"],
        unique=False,
    )
    op.create_index(op.f("ix_oauth_attempts_user_id"), "oauth_attempts", ["user_id"], unique=False)
    op.create_table(
        "usage_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("subject_key", sa.String(length=96), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("spent_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("operation_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_key", "category", "window_start", name="uq_usage_window"),
    )
    op.create_index(op.f("ix_usage_buckets_user_id"), "usage_buckets", ["user_id"], unique=False)
    op.create_table(
        "buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("purpose", sa.String(length=240), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gmail_account_id"], ["gmail_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gmail_account_id", "name", name="uq_bucket_account_name"),
    )
    op.create_index("ix_bucket_owner_active", "buckets", ["user_id", "archived"], unique=False)
    op.create_table(
        "email_threads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snippet", sa.String(length=500), nullable=False),
        sa.Column("latest_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmail_unread", sa.Boolean(), nullable=False),
        sa.Column("attachment_present", sa.Boolean(), nullable=False),
        sa.Column("content_version", sa.String(length=64), nullable=False),
        sa.Column("processing_state", sa.String(length=32), nullable=False),
        sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["gmail_account_id"], ["gmail_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gmail_account_id", "gmail_thread_id", name="uq_thread_provider_id"),
    )
    op.create_index(
        op.f("ix_email_threads_gmail_account_id"),
        "email_threads",
        ["gmail_account_id"],
        unique=False,
    )
    op.create_index(op.f("ix_email_threads_user_id"), "email_threads", ["user_id"], unique=False)
    op.create_index(
        "ix_thread_owner_latest", "email_threads", ["user_id", "latest_message_at"], unique=False
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("requested_limit", sa.Integer(), nullable=False),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["gmail_account_id"], ["gmail_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_run_owner_created", "processing_runs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "ai_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("input_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("output_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("actual_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    op.create_table(
        "bucket_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column("locked_by_user", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["bucket_id"], ["buckets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(
        op.f("ix_bucket_assignments_bucket_id"), "bucket_assignments", ["bucket_id"], unique=False
    )
    op.create_index(
        op.f("ix_bucket_assignments_user_id"), "bucket_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "gmail_label_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("gmail_label_id", sa.String(length=128), nullable=False),
        sa.Column("desired_name", sa.String(length=225), nullable=False),
        sa.Column("sync_status", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(["bucket_id"], ["buckets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket_id"),
    )
    op.create_index(
        op.f("ix_gmail_label_mappings_user_id"), "gmail_label_mappings", ["user_id"], unique=False
    )
    op.create_table(
        "message_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=128), nullable=False),
        sa.Column("internet_message_id", sa.String(length=998), nullable=True),
        sa.Column("sender_name", sa.String(length=320), nullable=False),
        sa.Column("sender_address", sa.String(length=320), nullable=False),
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmail_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attachment_present", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["gmail_account_id"], ["gmail_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gmail_account_id", "gmail_message_id", name="uq_message_provider_id"),
    )
    op.create_index(
        op.f("ix_message_references_user_id"), "message_references", ["user_id"], unique=False
    )
    op.create_index(
        "ix_message_thread_time", "message_references", ["thread_id", "sent_at"], unique=False
    )
    op.create_table(
        "sender_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("gmail_account_id", sa.UUID(), nullable=False),
        sa.Column("sender_address", sa.String(length=320), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["bucket_id"], ["buckets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gmail_account_id", "sender_address", name="uq_sender_rule_account"),
    )
    op.create_index(op.f("ix_sender_rules_user_id"), "sender_rules", ["user_id"], unique=False)
    op.create_table(
        "thread_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.String(length=700), nullable=False),
        sa.Column("action_required", sa.Boolean(), nullable=False),
        sa.Column("action_type", sa.String(length=24), nullable=False),
        sa.Column("action_text", sa.String(length=500), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source_message_id", sa.String(length=128), nullable=True),
        sa.Column("uncertain", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("content_version", sa.String(length=64), nullable=False),
        sa.Column("action_status", sa.String(length=24), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(
        op.f("ix_thread_analyses_user_id"), "thread_analyses", ["user_id"], unique=False
    )
    op.create_table(
        "thread_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("content_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(
        op.f("ix_thread_embeddings_user_id"), "thread_embeddings", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_embeddings_user_id"), table_name="thread_embeddings")
    op.drop_table("thread_embeddings")
    op.drop_index(op.f("ix_thread_analyses_user_id"), table_name="thread_analyses")
    op.drop_table("thread_analyses")
    op.drop_index(op.f("ix_sender_rules_user_id"), table_name="sender_rules")
    op.drop_table("sender_rules")
    op.drop_index("ix_message_thread_time", table_name="message_references")
    op.drop_index(op.f("ix_message_references_user_id"), table_name="message_references")
    op.drop_table("message_references")
    op.drop_index(op.f("ix_gmail_label_mappings_user_id"), table_name="gmail_label_mappings")
    op.drop_table("gmail_label_mappings")
    op.drop_index(op.f("ix_bucket_assignments_user_id"), table_name="bucket_assignments")
    op.drop_index(op.f("ix_bucket_assignments_bucket_id"), table_name="bucket_assignments")
    op.drop_table("bucket_assignments")
    op.drop_index(op.f("ix_ai_usage_user_id"), table_name="ai_usage")
    op.drop_table("ai_usage")
    op.drop_index("ix_run_owner_created", table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_index("ix_thread_owner_latest", table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_user_id"), table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_gmail_account_id"), table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_index("ix_bucket_owner_active", table_name="buckets")
    op.drop_table("buckets")
    op.drop_index(op.f("ix_usage_buckets_user_id"), table_name="usage_buckets")
    op.drop_table("usage_buckets")
    op.drop_index(op.f("ix_oauth_attempts_user_id"), table_name="oauth_attempts")
    op.drop_index(op.f("ix_oauth_attempts_browser_session_id"), table_name="oauth_attempts")
    op.drop_table("oauth_attempts")
    op.drop_index(op.f("ix_gmail_accounts_user_id"), table_name="gmail_accounts")
    op.drop_table("gmail_accounts")
    op.drop_table("users")
    op.drop_index(op.f("ix_security_audit_events_resource_id"), table_name="security_audit_events")
    op.drop_index(op.f("ix_security_audit_events_event_type"), table_name="security_audit_events")
    op.drop_index(op.f("ix_security_audit_events_created_at"), table_name="security_audit_events")
    op.drop_index(op.f("ix_security_audit_events_actor_id"), table_name="security_audit_events")
    op.drop_table("security_audit_events")
    # ### end Alembic commands ###
